project:
  type: website
  output-dir: _site

website:
  title: "Estadística"
  description: "Carrera en Ciencias Navales · Tercer Año"
  page-navigation: true
  reader-mode: true
  navbar:
    background: "#21295C"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Inicio
      - text: "Unidad 1"
        menu:
          - href: unidad-1/tema-1-1.qmd
            text: "Tema 1.1 · Introducción a la Estadística"
  sidebar:
    style: docked
    background: light
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Presentación del curso"
      - section: "Unidad 1 · Estadística descriptiva y probabilidades"
        contents:
          - href: unidad-1/tema-1-1.qmd
            text: "Tema 1.1 · Introducción a la Estadística"
  page-footer:
    background: light
    left: "Estadística · Ciencias Navales · Unidad 1"
    right: "Dr. Daniel Lagos Llaguno"

format:
  live-html:
    theme: [cosmo, estilo.scss]
    toc: true
    toc-depth: 3
    toc-title: "En esta página"
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    fig-align: center

live:
  show-hints: true
  show-solutions: true

engine: knitr
